/*
 * Pre-tournament strength rating per team (0–100). Used by both the
 * home-page "Title contenders" ranking and the tournament-live
 * widget's match-of-the-day picker.
 */
export const BASE_RATING = {
    'Argentina': 90,
    'France': 87,
    'Brazil': 85,
    'Spain': 84,
    'England': 82,
    'Portugal': 80,
    'Germany': 80,
    'Netherlands': 78,
    'Belgium': 72,
    'Croatia': 70,
    'Uruguay': 70,
    'Colombia': 68,
    'Morocco': 68,
    'Switzerland': 65,
    'Japan': 64,
    'Mexico': 64,
    'USA': 62,
    'Senegal': 58,
    'Norway': 57,
    'Australia': 55,
    'Canada': 55,
    'Ecuador': 55,
    'South Korea': 54,
    'Austria': 54,
    'Ivory Coast': 52,
    'Iran': 52,
    'Sweden': 52,
    'Egypt': 52,
    'Türkiye': 52,
    'Paraguay': 48,
    'Saudi Arabia': 45,
    'Algeria': 44,
    'Scotland': 44,
    'DR Congo': 44,
    'Ghana': 44,
    'Bosnia': 42,
    'Tunisia': 42,
    'Uzbekistan': 40,
    'Czechia': 40,
    'Qatar': 38,
    'Panama': 34,
    'New Zealand': 32,
    'South Africa': 32,
    'Iraq': 30,
    'Jordan': 28,
    'Cape Verde': 26,
    'Haiti': 25,
    'Curaçao': 22
};
